import Image from "next/image";
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

import { Providers } from "@/providers/Providers";

import "./globals.css";

const publicSans = Public_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Challenge Ualá",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          :root {
            --font-public-sans: ${publicSans.style.fontFamily};
          }
        `}</style>
      </head>
      <body className="antialiased m-auto h-screen" style={{ fontFamily: publicSans.style.fontFamily }}>
        <Providers>
          <nav className="fixed w-full top-0 z-[100]">
            <div className="w-full absolute -top-1 left-0">
              <div className="relative h-[56px]">
                <Image
                  className="w-full object-contain sm:object-cover"
                  src="/nav-bar_wave/TAB_Container.svg"
                  alt="Nav Bar"
                  fill
                  style={{ filter: "drop-shadow(0px 1px 1px #DEE2EC)" }}
                />
              </div>
              <div className="relative">
                <Image
                  src="/nav-bar_wave/Subtract.svg"
                  className="absolute -top-1 right-0 sm:top-0"
                  style={{ filter: "drop-shadow(0px 1px 1px #DEE2EC)" }}
                  alt="Nav Bar"
                  width={56}
                  height={56}
                />
              </div>
            </div>
            <div className="w-10/12 m-auto">
              <div className="flex">
                <Image className="h-[50px] my-auto" src="/nav-bar/hamburguer.svg" alt="Nav Bar" width={16} height={16} />
              </div>
            </div>
          </nav>
          <main className="w-10/12 m-auto pt-[72px]">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
