import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

import { Providers } from "@/providers/Providers";
import { NavBar } from "@/common/NavBar";

import "./globals.css";
import { RoutesSideBar } from "@/common/NavBar/RoutesSideBar";

const publicSans = Public_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Challenge Ualá",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          :root {
            --font-public-sans: ${publicSans.style.fontFamily};
          }
        `}</style>
      </head>
      <body
        className="antialiased m-auto h-screen"
        style={{ fontFamily: publicSans.style.fontFamily }}
      >
        <Providers>
          <NavBar />
          <div className="flex">
            <RoutesSideBar />
            <main className="w-10/12 sm:w-5/12 m-auto pt-[88px]">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
